//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace bigbus.checkout.EcrWServiceRefV3 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Api", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListUID))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListID))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseRequest))]
    public partial class Api : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ProductListOperationCompleted;
        
        private System.Threading.SendOrPostCallback AvailabilityCheckOperationCompleted;
        
        private System.Threading.SendOrPostCallback BookingOperationCompleted;
        
        private System.Threading.SendOrPostCallback BookingCancellationOperationCompleted;
        
        private System.Threading.SendOrPostCallback BookingStatusOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Api() {
            this.Url = global::bigbus.checkout.Properties.Settings.Default.bigbus_checkout_EcrWServiceRefV3_Api;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ProductListCompletedEventHandler ProductListCompleted;
        
        /// <remarks/>
        public event AvailabilityCheckCompletedEventHandler AvailabilityCheckCompleted;
        
        /// <remarks/>
        public event BookingCompletedEventHandler BookingCompleted;
        
        /// <remarks/>
        public event BookingCancellationCompletedEventHandler BookingCancellationCompleted;
        
        /// <remarks/>
        public event BookingStatusCompletedEventHandler BookingStatusCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IApi/ProductList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ProductListResponse ProductList([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ProductListRequest ProductListRequest) {
            object[] results = this.Invoke("ProductList", new object[] {
                        ProductListRequest});
            return ((ProductListResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ProductListAsync(ProductListRequest ProductListRequest) {
            this.ProductListAsync(ProductListRequest, null);
        }
        
        /// <remarks/>
        public void ProductListAsync(ProductListRequest ProductListRequest, object userState) {
            if ((this.ProductListOperationCompleted == null)) {
                this.ProductListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProductListOperationCompleted);
            }
            this.InvokeAsync("ProductList", new object[] {
                        ProductListRequest}, this.ProductListOperationCompleted, userState);
        }
        
        private void OnProductListOperationCompleted(object arg) {
            if ((this.ProductListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProductListCompleted(this, new ProductListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IApi/AvailabilityCheck", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AvailabilityResponse AvailabilityCheck([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] AvailabilityRequest AvailabilityRequest) {
            object[] results = this.Invoke("AvailabilityCheck", new object[] {
                        AvailabilityRequest});
            return ((AvailabilityResponse)(results[0]));
        }
        
        /// <remarks/>
        public void AvailabilityCheckAsync(AvailabilityRequest AvailabilityRequest) {
            this.AvailabilityCheckAsync(AvailabilityRequest, null);
        }
        
        /// <remarks/>
        public void AvailabilityCheckAsync(AvailabilityRequest AvailabilityRequest, object userState) {
            if ((this.AvailabilityCheckOperationCompleted == null)) {
                this.AvailabilityCheckOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAvailabilityCheckOperationCompleted);
            }
            this.InvokeAsync("AvailabilityCheck", new object[] {
                        AvailabilityRequest}, this.AvailabilityCheckOperationCompleted, userState);
        }
        
        private void OnAvailabilityCheckOperationCompleted(object arg) {
            if ((this.AvailabilityCheckCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AvailabilityCheckCompleted(this, new AvailabilityCheckCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IApi/Booking", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public BookingResponse Booking([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] BookingRequest BookingRequest) {
            object[] results = this.Invoke("Booking", new object[] {
                        BookingRequest});
            return ((BookingResponse)(results[0]));
        }
        
        /// <remarks/>
        public void BookingAsync(BookingRequest BookingRequest) {
            this.BookingAsync(BookingRequest, null);
        }
        
        /// <remarks/>
        public void BookingAsync(BookingRequest BookingRequest, object userState) {
            if ((this.BookingOperationCompleted == null)) {
                this.BookingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBookingOperationCompleted);
            }
            this.InvokeAsync("Booking", new object[] {
                        BookingRequest}, this.BookingOperationCompleted, userState);
        }
        
        private void OnBookingOperationCompleted(object arg) {
            if ((this.BookingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BookingCompleted(this, new BookingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IApi/BookingCancellation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public BookingCancellationResponse BookingCancellation([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] BookingCancellationRequest BookingCancellationRequest) {
            object[] results = this.Invoke("BookingCancellation", new object[] {
                        BookingCancellationRequest});
            return ((BookingCancellationResponse)(results[0]));
        }
        
        /// <remarks/>
        public void BookingCancellationAsync(BookingCancellationRequest BookingCancellationRequest) {
            this.BookingCancellationAsync(BookingCancellationRequest, null);
        }
        
        /// <remarks/>
        public void BookingCancellationAsync(BookingCancellationRequest BookingCancellationRequest, object userState) {
            if ((this.BookingCancellationOperationCompleted == null)) {
                this.BookingCancellationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBookingCancellationOperationCompleted);
            }
            this.InvokeAsync("BookingCancellation", new object[] {
                        BookingCancellationRequest}, this.BookingCancellationOperationCompleted, userState);
        }
        
        private void OnBookingCancellationOperationCompleted(object arg) {
            if ((this.BookingCancellationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BookingCancellationCompleted(this, new BookingCancellationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IApi/BookingStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public BookingStatusResponse BookingStatus([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] BookingStatusRequest BookingStatusRequest) {
            object[] results = this.Invoke("BookingStatus", new object[] {
                        BookingStatusRequest});
            return ((BookingStatusResponse)(results[0]));
        }
        
        /// <remarks/>
        public void BookingStatusAsync(BookingStatusRequest BookingStatusRequest) {
            this.BookingStatusAsync(BookingStatusRequest, null);
        }
        
        /// <remarks/>
        public void BookingStatusAsync(BookingStatusRequest BookingStatusRequest, object userState) {
            if ((this.BookingStatusOperationCompleted == null)) {
                this.BookingStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBookingStatusOperationCompleted);
            }
            this.InvokeAsync("BookingStatus", new object[] {
                        BookingStatusRequest}, this.BookingStatusOperationCompleted, userState);
        }
        
        private void OnBookingStatusOperationCompleted(object arg) {
            if ((this.BookingStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BookingStatusCompleted(this, new BookingStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BBC3")]
    public partial class ProductListRequest : BaseRequest {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BookingStatusRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BookingCancellationRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BookingRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AvailabilityRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductListRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BBC3")]
    public partial class BaseRequest {
        
        private string agentCodeField;
        
        private string agentUIDField;
        
        private string apiKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AgentCode {
            get {
                return this.agentCodeField;
            }
            set {
                this.agentCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AgentUID {
            get {
                return this.agentUIDField;
            }
            set {
                this.agentUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ApiKey {
            get {
                return this.apiKeyField;
            }
            set {
                this.apiKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BBC3")]
    public partial class BarcodeDetail {
        
        private int branchIDField;
        
        private decimal priceField;
        
        private string productDimensionUIDField;
        
        private int qTYField;
        
        private string sysIDField;
        
        private System.DateTime validFromField;
        
        /// <remarks/>
        public int BranchID {
            get {
                return this.branchIDField;
            }
            set {
                this.branchIDField = value;
            }
        }
        
        /// <remarks/>
        public decimal Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ProductDimensionUID {
            get {
                return this.productDimensionUIDField;
            }
            set {
                this.productDimensionUIDField = value;
            }
        }
        
        /// <remarks/>
        public int QTY {
            get {
                return this.qTYField;
            }
            set {
                this.qTYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SysID {
            get {
                return this.sysIDField;
            }
            set {
                this.sysIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ValidFrom {
            get {
                return this.validFromField;
            }
            set {
                this.validFromField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BBC3")]
    public partial class Barcode {
        
        private string barcodeAsTextField;
        
        private BarcodeDetail[] barcodeDetailsField;
        
        private string transactionReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BarcodeAsText {
            get {
                return this.barcodeAsTextField;
            }
            set {
                this.barcodeAsTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public BarcodeDetail[] BarcodeDetails {
            get {
                return this.barcodeDetailsField;
            }
            set {
                this.barcodeDetailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TransactionReference {
            get {
                return this.transactionReferenceField;
            }
            set {
                this.transactionReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BBC3")]
    public partial class Price {
        
        private bool activeField;
        
        private decimal amountField;
        
        private string currencyCodeField;
        
        private string currencyUIDField;
        
        private string priceLevelUIDField;
        
        private string productDimensionUIDField;
        
        private decimal salePriceField;
        
        private int sortOrderField;
        
        private string taxGroupUIDField;
        
        private string uIDField;
        
        private System.DateTime validFromField;
        
        /// <remarks/>
        public bool Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CurrencyCode {
            get {
                return this.currencyCodeField;
            }
            set {
                this.currencyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CurrencyUID {
            get {
                return this.currencyUIDField;
            }
            set {
                this.currencyUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PriceLevelUID {
            get {
                return this.priceLevelUIDField;
            }
            set {
                this.priceLevelUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ProductDimensionUID {
            get {
                return this.productDimensionUIDField;
            }
            set {
                this.productDimensionUIDField = value;
            }
        }
        
        /// <remarks/>
        public decimal SalePrice {
            get {
                return this.salePriceField;
            }
            set {
                this.salePriceField = value;
            }
        }
        
        /// <remarks/>
        public int SortOrder {
            get {
                return this.sortOrderField;
            }
            set {
                this.sortOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TaxGroupUID {
            get {
                return this.taxGroupUIDField;
            }
            set {
                this.taxGroupUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UID {
            get {
                return this.uIDField;
            }
            set {
                this.uIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ValidFrom {
            get {
                return this.validFromField;
            }
            set {
                this.validFromField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BBC3")]
    public partial class ProductDimension {
        
        private bool activeField;
        
        private bool isAllField;
        
        private string nameField;
        
        private Price[] pricesField;
        
        private string productUIDField;
        
        private int sortOrderField;
        
        private string sysIDField;
        
        private string ticketTypeUIDField;
        
        private string uIDField;
        
        /// <remarks/>
        public bool Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        public bool IsAll {
            get {
                return this.isAllField;
            }
            set {
                this.isAllField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Price[] Prices {
            get {
                return this.pricesField;
            }
            set {
                this.pricesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ProductUID {
            get {
                return this.productUIDField;
            }
            set {
                this.productUIDField = value;
            }
        }
        
        /// <remarks/>
        public int SortOrder {
            get {
                return this.sortOrderField;
            }
            set {
                this.sortOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SysID {
            get {
                return this.sysIDField;
            }
            set {
                this.sysIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TicketTypeUID {
            get {
                return this.ticketTypeUIDField;
            }
            set {
                this.ticketTypeUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UID {
            get {
                return this.uIDField;
            }
            set {
                this.uIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BBC3")]
    public partial class Product {
        
        private bool activeField;
        
        private int branchIDField;
        
        private bool monitorableField;
        
        private string nameField;
        
        private string pictureField;
        
        private string printNameField;
        
        private string printTextField;
        
        private ProductDimension[] productDimensionsField;
        
        private string productGroupUIDField;
        
        private int productTypeIDField;
        
        private int sortOrderField;
        
        private string sysIDField;
        
        private string taxGroupUIDField;
        
        private string uIDField;
        
        /// <remarks/>
        public bool Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        public int BranchID {
            get {
                return this.branchIDField;
            }
            set {
                this.branchIDField = value;
            }
        }
        
        /// <remarks/>
        public bool Monitorable {
            get {
                return this.monitorableField;
            }
            set {
                this.monitorableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Picture {
            get {
                return this.pictureField;
            }
            set {
                this.pictureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PrintName {
            get {
                return this.printNameField;
            }
            set {
                this.printNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PrintText {
            get {
                return this.printTextField;
            }
            set {
                this.printTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ProductDimension[] ProductDimensions {
            get {
                return this.productDimensionsField;
            }
            set {
                this.productDimensionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ProductGroupUID {
            get {
                return this.productGroupUIDField;
            }
            set {
                this.productGroupUIDField = value;
            }
        }
        
        /// <remarks/>
        public int ProductTypeID {
            get {
                return this.productTypeIDField;
            }
            set {
                this.productTypeIDField = value;
            }
        }
        
        /// <remarks/>
        public int SortOrder {
            get {
                return this.sortOrderField;
            }
            set {
                this.sortOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SysID {
            get {
                return this.sysIDField;
            }
            set {
                this.sysIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TaxGroupUID {
            get {
                return this.taxGroupUIDField;
            }
            set {
                this.taxGroupUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UID {
            get {
                return this.uIDField;
            }
            set {
                this.uIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TicketType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TaxGroup))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductGroup))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PriceLevel))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BBC3")]
    public partial class ListUID {
        
        private string nameField;
        
        private string uIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UID {
            get {
                return this.uIDField;
            }
            set {
                this.uIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BBC3")]
    public partial class TicketType : ListUID {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BBC3")]
    public partial class TaxGroup : ListUID {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BBC3")]
    public partial class ProductGroup : ListUID {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BBC3")]
    public partial class PriceLevel : ListUID {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Branch))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BBC3")]
    public partial class ListID {
        
        private string idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BBC3")]
    public partial class ProductType : ListID {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BBC3")]
    public partial class Branch : ListID {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BBC3")]
    public partial class Lists {
        
        private Branch[] branchesField;
        
        private PriceLevel[] priceLevelsField;
        
        private ProductGroup[] productGroupsField;
        
        private ProductType[] productTypesField;
        
        private TaxGroup[] taxGroupsField;
        
        private TicketType[] ticketTypesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Branch[] Branches {
            get {
                return this.branchesField;
            }
            set {
                this.branchesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public PriceLevel[] PriceLevels {
            get {
                return this.priceLevelsField;
            }
            set {
                this.priceLevelsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ProductGroup[] ProductGroups {
            get {
                return this.productGroupsField;
            }
            set {
                this.productGroupsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ProductType[] ProductTypes {
            get {
                return this.productTypesField;
            }
            set {
                this.productTypesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public TaxGroup[] TaxGroups {
            get {
                return this.taxGroupsField;
            }
            set {
                this.taxGroupsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public TicketType[] TicketTypes {
            get {
                return this.ticketTypesField;
            }
            set {
                this.ticketTypesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BookingStatusResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BookingCancellationResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BookingResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AvailabilityResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductListResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BBC3")]
    public partial class BaseResponse {
        
        private string errorDescriptionField;
        
        private int statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ErrorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BBC3")]
    public partial class BookingStatusResponse : BaseResponse {
        
        private string bookingStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BookingStatus {
            get {
                return this.bookingStatusField;
            }
            set {
                this.bookingStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BBC3")]
    public partial class BookingCancellationResponse : BaseResponse {
        
        private string transactionReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TransactionReference {
            get {
                return this.transactionReferenceField;
            }
            set {
                this.transactionReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BBC3")]
    public partial class BookingResponse : BaseResponse {
        
        private Barcode[] barcodesField;
        
        private BookingTransactionDetail[] transactionDetailsField;
        
        private string transactionReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Barcode[] Barcodes {
            get {
                return this.barcodesField;
            }
            set {
                this.barcodesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public BookingTransactionDetail[] TransactionDetails {
            get {
                return this.transactionDetailsField;
            }
            set {
                this.transactionDetailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TransactionReference {
            get {
                return this.transactionReferenceField;
            }
            set {
                this.transactionReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BBC3")]
    public partial class BookingTransactionDetail {
        
        private Account accountField;
        
        private string currencyCodeField;
        
        private decimal discountAmountField;
        
        private bool discountAmountFieldSpecified;
        
        private string discountCodeField;
        
        private string notesField;
        
        private decimal priceField;
        
        private string productDimensionUIDField;
        
        private string promoCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Account Account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CurrencyCode {
            get {
                return this.currencyCodeField;
            }
            set {
                this.currencyCodeField = value;
            }
        }
        
        /// <remarks/>
        public decimal DiscountAmount {
            get {
                return this.discountAmountField;
            }
            set {
                this.discountAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DiscountAmountSpecified {
            get {
                return this.discountAmountFieldSpecified;
            }
            set {
                this.discountAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DiscountCode {
            get {
                return this.discountCodeField;
            }
            set {
                this.discountCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
        
        /// <remarks/>
        public decimal Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ProductDimensionUID {
            get {
                return this.productDimensionUIDField;
            }
            set {
                this.productDimensionUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PromoCode {
            get {
                return this.promoCodeField;
            }
            set {
                this.promoCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BBC3")]
    public partial class Account {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BBC3")]
    public partial class AvailabilityResponse : BaseResponse {
        
        private AvailabilityTransactionDetail[] transactionDetailsField;
        
        private string transactionReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public AvailabilityTransactionDetail[] TransactionDetails {
            get {
                return this.transactionDetailsField;
            }
            set {
                this.transactionDetailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TransactionReference {
            get {
                return this.transactionReferenceField;
            }
            set {
                this.transactionReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BBC3")]
    public partial class AvailabilityTransactionDetail {
        
        private string productDimensionUIDField;
        
        private int qTYField;
        
        private System.DateTime validFromField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ProductDimensionUID {
            get {
                return this.productDimensionUIDField;
            }
            set {
                this.productDimensionUIDField = value;
            }
        }
        
        /// <remarks/>
        public int QTY {
            get {
                return this.qTYField;
            }
            set {
                this.qTYField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ValidFrom {
            get {
                return this.validFromField;
            }
            set {
                this.validFromField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BBC3")]
    public partial class ProductListResponse : BaseResponse {
        
        private Lists listsField;
        
        private Product[] productsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Lists Lists {
            get {
                return this.listsField;
            }
            set {
                this.listsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Product[] Products {
            get {
                return this.productsField;
            }
            set {
                this.productsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BBC3")]
    public partial class BookingStatusRequest : BaseRequest {
        
        private string transactionReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TransactionReference {
            get {
                return this.transactionReferenceField;
            }
            set {
                this.transactionReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BBC3")]
    public partial class BookingCancellationRequest : BaseRequest {
        
        private string transactionReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TransactionReference {
            get {
                return this.transactionReferenceField;
            }
            set {
                this.transactionReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BBC3")]
    public partial class BookingRequest : BaseRequest {
        
        private string supplierTranReferenceField;
        
        private BookingTransactionDetail[] transactionDetailsField;
        
        private string transactionReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SupplierTranReference {
            get {
                return this.supplierTranReferenceField;
            }
            set {
                this.supplierTranReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public BookingTransactionDetail[] TransactionDetails {
            get {
                return this.transactionDetailsField;
            }
            set {
                this.transactionDetailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TransactionReference {
            get {
                return this.transactionReferenceField;
            }
            set {
                this.transactionReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BBC3")]
    public partial class AvailabilityRequest : BaseRequest {
        
        private AvailabilityTransactionDetail[] transactionDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public AvailabilityTransactionDetail[] TransactionDetails {
            get {
                return this.transactionDetailsField;
            }
            set {
                this.transactionDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ProductListCompletedEventHandler(object sender, ProductListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProductListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProductListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProductListResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductListResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void AvailabilityCheckCompletedEventHandler(object sender, AvailabilityCheckCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AvailabilityCheckCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AvailabilityCheckCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AvailabilityResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AvailabilityResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void BookingCompletedEventHandler(object sender, BookingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BookingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BookingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BookingResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BookingResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void BookingCancellationCompletedEventHandler(object sender, BookingCancellationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BookingCancellationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BookingCancellationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BookingCancellationResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BookingCancellationResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void BookingStatusCompletedEventHandler(object sender, BookingStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BookingStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BookingStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BookingStatusResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BookingStatusResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591