//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace bigbus.checkout.EcrServiceRef {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Api", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseTour))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseResponse))]
    public partial class Api : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback TourListOperationCompleted;
        
        private System.Threading.SendOrPostCallback AvailabilityOperationCompleted;
        
        private System.Threading.SendOrPostCallback BookingOperationCompleted;
        
        private System.Threading.SendOrPostCallback BookingAmendmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback BookingCancelationOperationCompleted;
        
        private System.Threading.SendOrPostCallback BookingStatusOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Api() {
            this.Url = global::bigbus.checkout.Properties.Settings.Default.bigbus_checkout_EcrServiceRef_Api;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event TourListCompletedEventHandler TourListCompleted;
        
        /// <remarks/>
        public event AvailabilityCompletedEventHandler AvailabilityCompleted;
        
        /// <remarks/>
        public event BookingCompletedEventHandler BookingCompleted;
        
        /// <remarks/>
        public event BookingAmendmentCompletedEventHandler BookingAmendmentCompleted;
        
        /// <remarks/>
        public event BookingCancelationCompletedEventHandler BookingCancelationCompleted;
        
        /// <remarks/>
        public event BookingStatusCompletedEventHandler BookingStatusCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IApi/TourList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TourListResponse TourList([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ApiKey) {
            object[] results = this.Invoke("TourList", new object[] {
                        ApiKey});
            return ((TourListResponse)(results[0]));
        }
        
        /// <remarks/>
        public void TourListAsync(string ApiKey) {
            this.TourListAsync(ApiKey, null);
        }
        
        /// <remarks/>
        public void TourListAsync(string ApiKey, object userState) {
            if ((this.TourListOperationCompleted == null)) {
                this.TourListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTourListOperationCompleted);
            }
            this.InvokeAsync("TourList", new object[] {
                        ApiKey}, this.TourListOperationCompleted, userState);
        }
        
        private void OnTourListOperationCompleted(object arg) {
            if ((this.TourListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TourListCompleted(this, new TourListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IApi/Availability", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AvailabilityResponse Availability([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ApiKey, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string SupplierProductCode, System.DateTime StartDate, [System.Xml.Serialization.XmlIgnoreAttribute()] bool StartDateSpecified, System.DateTime EndDate, [System.Xml.Serialization.XmlIgnoreAttribute()] bool EndDateSpecified) {
            object[] results = this.Invoke("Availability", new object[] {
                        ApiKey,
                        SupplierProductCode,
                        StartDate,
                        StartDateSpecified,
                        EndDate,
                        EndDateSpecified});
            return ((AvailabilityResponse)(results[0]));
        }
        
        /// <remarks/>
        public void AvailabilityAsync(string ApiKey, string SupplierProductCode, System.DateTime StartDate, bool StartDateSpecified, System.DateTime EndDate, bool EndDateSpecified) {
            this.AvailabilityAsync(ApiKey, SupplierProductCode, StartDate, StartDateSpecified, EndDate, EndDateSpecified, null);
        }
        
        /// <remarks/>
        public void AvailabilityAsync(string ApiKey, string SupplierProductCode, System.DateTime StartDate, bool StartDateSpecified, System.DateTime EndDate, bool EndDateSpecified, object userState) {
            if ((this.AvailabilityOperationCompleted == null)) {
                this.AvailabilityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAvailabilityOperationCompleted);
            }
            this.InvokeAsync("Availability", new object[] {
                        ApiKey,
                        SupplierProductCode,
                        StartDate,
                        StartDateSpecified,
                        EndDate,
                        EndDateSpecified}, this.AvailabilityOperationCompleted, userState);
        }
        
        private void OnAvailabilityOperationCompleted(object arg) {
            if ((this.AvailabilityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AvailabilityCompleted(this, new AvailabilityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IApi/Booking", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public BookingResponse Booking([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ApiKey, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] BookingRequest BookingRequest) {
            object[] results = this.Invoke("Booking", new object[] {
                        ApiKey,
                        BookingRequest});
            return ((BookingResponse)(results[0]));
        }
        
        /// <remarks/>
        public void BookingAsync(string ApiKey, BookingRequest BookingRequest) {
            this.BookingAsync(ApiKey, BookingRequest, null);
        }
        
        /// <remarks/>
        public void BookingAsync(string ApiKey, BookingRequest BookingRequest, object userState) {
            if ((this.BookingOperationCompleted == null)) {
                this.BookingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBookingOperationCompleted);
            }
            this.InvokeAsync("Booking", new object[] {
                        ApiKey,
                        BookingRequest}, this.BookingOperationCompleted, userState);
        }
        
        private void OnBookingOperationCompleted(object arg) {
            if ((this.BookingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BookingCompleted(this, new BookingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IApi/BookingAmendment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public BookingResponse BookingAmendment([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ApiKey, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string SupplierConfirmationNumber, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] BookingRequest BookingAmendmentRequest) {
            object[] results = this.Invoke("BookingAmendment", new object[] {
                        ApiKey,
                        SupplierConfirmationNumber,
                        BookingAmendmentRequest});
            return ((BookingResponse)(results[0]));
        }
        
        /// <remarks/>
        public void BookingAmendmentAsync(string ApiKey, string SupplierConfirmationNumber, BookingRequest BookingAmendmentRequest) {
            this.BookingAmendmentAsync(ApiKey, SupplierConfirmationNumber, BookingAmendmentRequest, null);
        }
        
        /// <remarks/>
        public void BookingAmendmentAsync(string ApiKey, string SupplierConfirmationNumber, BookingRequest BookingAmendmentRequest, object userState) {
            if ((this.BookingAmendmentOperationCompleted == null)) {
                this.BookingAmendmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBookingAmendmentOperationCompleted);
            }
            this.InvokeAsync("BookingAmendment", new object[] {
                        ApiKey,
                        SupplierConfirmationNumber,
                        BookingAmendmentRequest}, this.BookingAmendmentOperationCompleted, userState);
        }
        
        private void OnBookingAmendmentOperationCompleted(object arg) {
            if ((this.BookingAmendmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BookingAmendmentCompleted(this, new BookingAmendmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IApi/BookingCancelation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public BookingCancellationResponse BookingCancelation([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ApiKey, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string SupplierConfirmationNumber) {
            object[] results = this.Invoke("BookingCancelation", new object[] {
                        ApiKey,
                        SupplierConfirmationNumber});
            return ((BookingCancellationResponse)(results[0]));
        }
        
        /// <remarks/>
        public void BookingCancelationAsync(string ApiKey, string SupplierConfirmationNumber) {
            this.BookingCancelationAsync(ApiKey, SupplierConfirmationNumber, null);
        }
        
        /// <remarks/>
        public void BookingCancelationAsync(string ApiKey, string SupplierConfirmationNumber, object userState) {
            if ((this.BookingCancelationOperationCompleted == null)) {
                this.BookingCancelationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBookingCancelationOperationCompleted);
            }
            this.InvokeAsync("BookingCancelation", new object[] {
                        ApiKey,
                        SupplierConfirmationNumber}, this.BookingCancelationOperationCompleted, userState);
        }
        
        private void OnBookingCancelationOperationCompleted(object arg) {
            if ((this.BookingCancelationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BookingCancelationCompleted(this, new BookingCancelationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IApi/BookingStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BookingStatus([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ApiKey, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string SupplierConfirmationNumber) {
            object[] results = this.Invoke("BookingStatus", new object[] {
                        ApiKey,
                        SupplierConfirmationNumber});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BookingStatusAsync(string ApiKey, string SupplierConfirmationNumber) {
            this.BookingStatusAsync(ApiKey, SupplierConfirmationNumber, null);
        }
        
        /// <remarks/>
        public void BookingStatusAsync(string ApiKey, string SupplierConfirmationNumber, object userState) {
            if ((this.BookingStatusOperationCompleted == null)) {
                this.BookingStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBookingStatusOperationCompleted);
            }
            this.InvokeAsync("BookingStatus", new object[] {
                        ApiKey,
                        SupplierConfirmationNumber}, this.BookingStatusOperationCompleted, userState);
        }
        
        private void OnBookingStatusOperationCompleted(object arg) {
            if ((this.BookingStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BookingStatusCompleted(this, new BookingStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class TourListResponse : BaseResponse {
        
        private Tour[] tourField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Tour[] Tour {
            get {
                return this.tourField;
            }
            set {
                this.tourField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class Tour : BaseTour {
        
        private TourOption[] optionsField;
        
        private string supplierProductCodeField;
        
        private string supplierProductNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public TourOption[] Options {
            get {
                return this.optionsField;
            }
            set {
                this.optionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SupplierProductCode {
            get {
                return this.supplierProductCodeField;
            }
            set {
                this.supplierProductCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SupplierProductName {
            get {
                return this.supplierProductNameField;
            }
            set {
                this.supplierProductNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class TourOption {
        
        private string ageBandField;
        
        private decimal priceField;
        
        private bool priceFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AgeBand {
            get {
                return this.ageBandField;
            }
            set {
                this.ageBandField = value;
            }
        }
        
        /// <remarks/>
        public decimal Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PriceSpecified {
            get {
                return this.priceFieldSpecified;
            }
            set {
                this.priceFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class ContactInfo {
        
        private string contactNameField;
        
        private string contactTypeField;
        
        private string contactValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ContactName {
            get {
                return this.contactNameField;
            }
            set {
                this.contactNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ContactType {
            get {
                return this.contactTypeField;
            }
            set {
                this.contactTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ContactValue {
            get {
                return this.contactValueField;
            }
            set {
                this.contactValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class BookingRequest {
        
        private string agentCodeField;
        
        private decimal amountField;
        
        private bool amountFieldSpecified;
        
        private string bookingReferenceField;
        
        private ContactInfo contactInfoField;
        
        private string currencyCodeField;
        
        private string locationField;
        
        private string pickupPointField;
        
        private string requiredInfoField;
        
        private string specialRequirementField;
        
        private string supplierNoteField;
        
        private string supplierProductCodeField;
        
        private string tourDescriptionField;
        
        private string tourDurationField;
        
        private System.DateTime travelDateField;
        
        private bool travelDateFieldSpecified;
        
        private Traveller[] travellersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AgentCode {
            get {
                return this.agentCodeField;
            }
            set {
                this.agentCodeField = value;
            }
        }
        
        /// <remarks/>
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AmountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BookingReference {
            get {
                return this.bookingReferenceField;
            }
            set {
                this.bookingReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ContactInfo ContactInfo {
            get {
                return this.contactInfoField;
            }
            set {
                this.contactInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CurrencyCode {
            get {
                return this.currencyCodeField;
            }
            set {
                this.currencyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PickupPoint {
            get {
                return this.pickupPointField;
            }
            set {
                this.pickupPointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RequiredInfo {
            get {
                return this.requiredInfoField;
            }
            set {
                this.requiredInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SpecialRequirement {
            get {
                return this.specialRequirementField;
            }
            set {
                this.specialRequirementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SupplierNote {
            get {
                return this.supplierNoteField;
            }
            set {
                this.supplierNoteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SupplierProductCode {
            get {
                return this.supplierProductCodeField;
            }
            set {
                this.supplierProductCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TourDescription {
            get {
                return this.tourDescriptionField;
            }
            set {
                this.tourDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TourDuration {
            get {
                return this.tourDurationField;
            }
            set {
                this.tourDurationField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TravelDate {
            get {
                return this.travelDateField;
            }
            set {
                this.travelDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TravelDateSpecified {
            get {
                return this.travelDateFieldSpecified;
            }
            set {
                this.travelDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Traveller[] Travellers {
            get {
                return this.travellersField;
            }
            set {
                this.travellersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class Traveller {
        
        private string ageBandField;
        
        private string givenNameField;
        
        private bool leadTravellerField;
        
        private bool leadTravellerFieldSpecified;
        
        private decimal priceField;
        
        private bool priceFieldSpecified;
        
        private string surnameField;
        
        private string travellerBarcodeField;
        
        private int travellerIdentifierField;
        
        private bool travellerIdentifierFieldSpecified;
        
        private string travellerTitleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AgeBand {
            get {
                return this.ageBandField;
            }
            set {
                this.ageBandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GivenName {
            get {
                return this.givenNameField;
            }
            set {
                this.givenNameField = value;
            }
        }
        
        /// <remarks/>
        public bool LeadTraveller {
            get {
                return this.leadTravellerField;
            }
            set {
                this.leadTravellerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LeadTravellerSpecified {
            get {
                return this.leadTravellerFieldSpecified;
            }
            set {
                this.leadTravellerFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PriceSpecified {
            get {
                return this.priceFieldSpecified;
            }
            set {
                this.priceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TravellerBarcode {
            get {
                return this.travellerBarcodeField;
            }
            set {
                this.travellerBarcodeField = value;
            }
        }
        
        /// <remarks/>
        public int TravellerIdentifier {
            get {
                return this.travellerIdentifierField;
            }
            set {
                this.travellerIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TravellerIdentifierSpecified {
            get {
                return this.travellerIdentifierFieldSpecified;
            }
            set {
                this.travellerIdentifierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TravellerTitle {
            get {
                return this.travellerTitleField;
            }
            set {
                this.travellerTitleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class AvailabilityHold {
        
        private string expiryField;
        
        private string referenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Expiry {
            get {
                return this.expiryField;
            }
            set {
                this.expiryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TourAvailability))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Tour))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class BaseTour {
        
        private string tourDescriptionField;
        
        private string tourDurationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TourDescription {
            get {
                return this.tourDescriptionField;
            }
            set {
                this.tourDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TourDuration {
            get {
                return this.tourDurationField;
            }
            set {
                this.tourDurationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class TourAvailability : BaseTour {
        
        private AvailabilityHold availabilityHoldField;
        
        private int availabilityStatusField;
        
        private bool availabilityStatusFieldSpecified;
        
        private System.DateTime dateField;
        
        private bool dateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AvailabilityHold AvailabilityHold {
            get {
                return this.availabilityHoldField;
            }
            set {
                this.availabilityHoldField = value;
            }
        }
        
        /// <remarks/>
        public int AvailabilityStatus {
            get {
                return this.availabilityStatusField;
            }
            set {
                this.availabilityStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AvailabilityStatusSpecified {
            get {
                return this.availabilityStatusFieldSpecified;
            }
            set {
                this.availabilityStatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateSpecified {
            get {
                return this.dateFieldSpecified;
            }
            set {
                this.dateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransactiontStatus))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class RequestStatus {
        
        private string descriptionField;
        
        private int statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class TransactiontStatus : RequestStatus {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BookingCancellationResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BookingResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AvailabilityResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TourListResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class BaseResponse {
        
        private RequestStatus requestStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RequestStatus RequestStatus {
            get {
                return this.requestStatusField;
            }
            set {
                this.requestStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class BookingCancellationResponse : BaseResponse {
        
        private string authorField;
        
        private string bookingReferenceField;
        
        private string cancelDateField;
        
        private string reasonField;
        
        private string supplierConfirmationNumberField;
        
        private string supplierProductCodeField;
        
        private string supplierProductNameField;
        
        private TransactiontStatus transactionStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BookingReference {
            get {
                return this.bookingReferenceField;
            }
            set {
                this.bookingReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CancelDate {
            get {
                return this.cancelDateField;
            }
            set {
                this.cancelDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SupplierConfirmationNumber {
            get {
                return this.supplierConfirmationNumberField;
            }
            set {
                this.supplierConfirmationNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SupplierProductCode {
            get {
                return this.supplierProductCodeField;
            }
            set {
                this.supplierProductCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SupplierProductName {
            get {
                return this.supplierProductNameField;
            }
            set {
                this.supplierProductNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TransactiontStatus TransactionStatus {
            get {
                return this.transactionStatusField;
            }
            set {
                this.transactionStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class BookingResponse : BaseResponse {
        
        private string bookingBarcodeField;
        
        private string bookingReferenceField;
        
        private string bookingShortReferenceField;
        
        private string supplierConfirmationNumberField;
        
        private TransactiontStatus transactionStatusField;
        
        private Traveller[] travellersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BookingBarcode {
            get {
                return this.bookingBarcodeField;
            }
            set {
                this.bookingBarcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BookingReference {
            get {
                return this.bookingReferenceField;
            }
            set {
                this.bookingReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BookingShortReference {
            get {
                return this.bookingShortReferenceField;
            }
            set {
                this.bookingShortReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SupplierConfirmationNumber {
            get {
                return this.supplierConfirmationNumberField;
            }
            set {
                this.supplierConfirmationNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TransactiontStatus TransactionStatus {
            get {
                return this.transactionStatusField;
            }
            set {
                this.transactionStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Traveller[] Travellers {
            get {
                return this.travellersField;
            }
            set {
                this.travellersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class AvailabilityResponse : BaseResponse {
        
        private string supplierProductCodeField;
        
        private TourAvailability[] tourAvailabilityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SupplierProductCode {
            get {
                return this.supplierProductCodeField;
            }
            set {
                this.supplierProductCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public TourAvailability[] TourAvailability {
            get {
                return this.tourAvailabilityField;
            }
            set {
                this.tourAvailabilityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void TourListCompletedEventHandler(object sender, TourListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TourListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TourListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TourListResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TourListResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void AvailabilityCompletedEventHandler(object sender, AvailabilityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AvailabilityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AvailabilityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AvailabilityResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AvailabilityResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void BookingCompletedEventHandler(object sender, BookingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BookingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BookingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BookingResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BookingResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void BookingAmendmentCompletedEventHandler(object sender, BookingAmendmentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BookingAmendmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BookingAmendmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BookingResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BookingResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void BookingCancelationCompletedEventHandler(object sender, BookingCancelationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BookingCancelationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BookingCancelationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BookingCancellationResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BookingCancellationResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void BookingStatusCompletedEventHandler(object sender, BookingStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BookingStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BookingStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591