//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bigbus.checkout.Ecr1ServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Ecr1ServiceRef.IDts")]
    public interface IDts {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDts/Put", ReplyAction="http://tempuri.org/IDts/PutResponse")]
        bool Put(int RefNo, int AuthNo, string ProductCode, int Price, System.DateTime TransactionOn, System.DateTime ValidTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDts/Put", ReplyAction="http://tempuri.org/IDts/PutResponse")]
        System.Threading.Tasks.Task<bool> PutAsync(int RefNo, int AuthNo, string ProductCode, int Price, System.DateTime TransactionOn, System.DateTime ValidTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDts/PutEx", ReplyAction="http://tempuri.org/IDts/PutExResponse")]
        bool PutEx(int RefNo, int AuthNo, string ProductCode, int Price, System.DateTime TransactionOn, System.DateTime ValidTo, string AgentCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDts/PutEx", ReplyAction="http://tempuri.org/IDts/PutExResponse")]
        System.Threading.Tasks.Task<bool> PutExAsync(int RefNo, int AuthNo, string ProductCode, int Price, System.DateTime TransactionOn, System.DateTime ValidTo, string AgentCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDtsChannel : bigbus.checkout.Ecr1ServiceRef.IDts, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DtsClient : System.ServiceModel.ClientBase<bigbus.checkout.Ecr1ServiceRef.IDts>, bigbus.checkout.Ecr1ServiceRef.IDts {
        
        public DtsClient() {
        }
        
        public DtsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DtsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DtsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DtsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Put(int RefNo, int AuthNo, string ProductCode, int Price, System.DateTime TransactionOn, System.DateTime ValidTo) {
            return base.Channel.Put(RefNo, AuthNo, ProductCode, Price, TransactionOn, ValidTo);
        }
        
        public System.Threading.Tasks.Task<bool> PutAsync(int RefNo, int AuthNo, string ProductCode, int Price, System.DateTime TransactionOn, System.DateTime ValidTo) {
            return base.Channel.PutAsync(RefNo, AuthNo, ProductCode, Price, TransactionOn, ValidTo);
        }
        
        public bool PutEx(int RefNo, int AuthNo, string ProductCode, int Price, System.DateTime TransactionOn, System.DateTime ValidTo, string AgentCode) {
            return base.Channel.PutEx(RefNo, AuthNo, ProductCode, Price, TransactionOn, ValidTo, AgentCode);
        }
        
        public System.Threading.Tasks.Task<bool> PutExAsync(int RefNo, int AuthNo, string ProductCode, int Price, System.DateTime TransactionOn, System.DateTime ValidTo, string AgentCode) {
            return base.Channel.PutExAsync(RefNo, AuthNo, ProductCode, Price, TransactionOn, ValidTo, AgentCode);
        }
    }
}
